version: '3.8'

services:
  user-api:
    image: ${DOCKER_USERNAME}/sycls-user-api:latest
    deploy:
      replicas: 2  # 동시에 실행할 인스턴스 수
      update_config:
        parallelism: 1  # 한 번에 업데이트할 인스턴스 수
        order: start-first  # 새로운 인스턴스를 먼저 시작한 후, 오래된 인스턴스를 중지
    ports:
      - "8080:8080"
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - DB_URL=localhost:3306
    restart: always
