version: '3.8'

services:
  admin-api:
    image: ${DOCKER_USERNAME}/sycls-admin-api:latest
    deploy:
      replicas: 2  # 동시에 실행할 인스턴스 수
      update_config:
        parallelism: 1  # 한 번에 업데이트할 인스턴스 수
        order: start-first  # 새로운 인스턴스를 먼저 시작한 후, 오래된 인스턴스를 중지
    ports:
      - "8081:8081"
    restart: always
